language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
      env: [FRONTEND=2.074]
    - d: dmd-beta
      env: [FRONTEND=2.074]
    - d: dmd
      env: [FRONTEND=2.074]
    - d: dmd-2.074.0
      env: [FRONTEND=2.074]
    - d: dmd-2.073.0
      env:
        - [FRONTEND=2.073]
        - [COVERAGE=true]
    - d: dmd-2.072.2
      env: [FRONTEND=2.072]
    - d: dmd-2.071.2
      env: [FRONTEND=2.071]
    - d: dmd-2.070.2
      env: [FRONTEND=2.070]
    - d: dmd-2.069.2
      env: [FRONTEND=2.069]
    - d: dmd-2.068.2
      env: [FRONTEND=2.068]
    - d: dmd-2.067.1
      env: [FRONTEND=2.067]
    - d: dmd-2.066.1
      env: [FRONTEND=2.066]
    - d: dmd-2.065.0
      env: [FRONTEND=2.065]
    - d: ldc-beta
      env: [FRONTEND=2.073]
    - d: ldc
      env: [FRONTEND=2.072]
    - d: ldc-1.2.0
      env: [FRONTEND=2.072]
    - d: ldc-1.1.0
      env: [FRONTEND=2.071]
    - d: ldc-1.0.0
      env: [FRONTEND=2.070]
    - d: ldc-0.17.2
      env: [FRONTEND=2.068]
    - d: gdc
      env: [FRONTEND=2.068]
    - d: gdc-5.2.0
      env: [FRONTEND=2.066]
    - d: gdc-4.9.2
      env: [FRONTEND=2.066]
    - d: gdc-4.9.0
      env: [FRONTEND=2.065]

  allow_failures:
    - d: gdc

script:
  - ./travis-ci.sh
